# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
  cfn-guard:
    needs: checkout
    runs-on: ubuntu-latest
    container:
      image: public.ecr.aws/aws-cloudformation/cloudformation-guard:3.0.3
      volumes:
        - ${{ github.workspace }}:/workspace
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (/usr/src/cloudformation-guard/cfn-guard validate -d /workspace/cfn/template.yml -r /workspace/guard-files/rule.guard)
    
          
